/* The region registry.
 *
 * COUNTRIES is generated by scripts/build_regions.py from Our World in Data's
 * republication of Ember's Global Electricity Review, joined to country
 * centroids. OPERATORS are sub-national grids that no country dataset covers.
 *
 * Great Britain is the only entry with an official public carbon-intensity
 * feed, so it is the only one that gets tier "official". Everywhere else the
 * model runs on live weather and is level-calibrated to that grid's published
 * annual mean.
 */

import { COUNTRIES, OPERATORS } from "./regions.generated.js";

// Great Britain is what the model was trained on, and it publishes a forecast.
const GB = {
  code: "GB",
  name: "Great Britain",
  lat: 54.0,
  lon: -2.0,
  mean: 124,
  official: true,
};

function build() {
  const out = { GB };
  for (const o of OPERATORS) out[o.code] = { ...o };
  for (const c of COUNTRIES) {
    if (c.code === "GB") continue; // the hand-tuned GB entry wins
    out[c.code] = { ...c };
  }
  return out;
}

export const REGIONS = build();

export const REGION_LIST = Object.values(REGIONS).sort((a, b) => {
  // Great Britain first because it is the validated one, then operators, then
  // countries alphabetically.
  if (a.code === "GB") return -1;
  if (b.code === "GB") return 1;
  if (!!a.operator !== !!b.operator) return a.operator ? -1 : 1;
  return a.name.localeCompare(b.name);
});

/* Combining diacritical marks, U+0300 to U+036F.
 *
 * Defensive rather than load-bearing today: the Ember dataset spells every one
 * of the 214 names in plain ASCII ("Cote d'Ivoire", "Reunion"), so nothing in
 * it currently needs folding. It costs nothing and means a future data source
 * with accented names does not quietly break the search. */
const COMBINING = /[̀-ͯ]/g;
const fold = (s) => s.trim().toLowerCase().normalize("NFKD").replace(COMBINING, "");

/** Accent-insensitive substring search, so "curacao" finds "Curaçao". */
export function searchRegions(query, limit = 40) {
  const q = fold(query);
  if (!q) return REGION_LIST.slice(0, limit);
  const hits = [];
  for (const r of REGION_LIST) {
    const name = fold(r.name);
    const idx = name.indexOf(q);
    if (idx === 0) hits.push([0, r]);
    else if (idx > 0) hits.push([1, r]);
    else if (r.code.toLowerCase() === q) hits.push([0, r]);
  }
  return hits.sort((a, b) => a[0] - b[0] || a[1].name.localeCompare(b[1].name))
    .slice(0, limit)
    .map(([, r]) => r);
}

export const TIER_COPY = {
  official: "Published by the grid operator.",
  modelled: "GridShift model on live weather.",
  transferred: "Model transferred from Great Britain and level-calibrated.",
};

export const REGION_COUNT = REGION_LIST.length;
